# Step 1: Build the Go application
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o blog-app cmd/app/main.go

# Step 2: Run the Go application
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/blog-app .
COPY --from=builder /app/config ./config
COPY --from=builder /app/migrations ./migrations
EXPOSE 8080
CMD ["./blog-app"]